spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estatesale
    username: estatesale
    password: estatesale
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true

server:
  servlet:
    context-path: /api
